#ifndef AGPU_TEXTURE_FORMATS_COMMON_HPP
#define AGPU_TEXTURE_FORMATS_COMMON_HPP

#include "AGPU/agpu.h"

inline size_t pixelSizeOfTextureFormat(agpu_texture_format format)
{
    switch(format)
    {
    case AGPU_TEXTURE_FORMAT_UNKNOWN:
        return 0;

	case AGPU_TEXTURE_FORMAT_R32G32B32A32_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R32G32B32A32_FLOAT:
	case AGPU_TEXTURE_FORMAT_R32G32B32A32_UINT:
	case AGPU_TEXTURE_FORMAT_R32G32B32A32_SINT:
        return 16;

	case AGPU_TEXTURE_FORMAT_R32G32B32_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R32G32B32_FLOAT:
	case AGPU_TEXTURE_FORMAT_R32G32B32_UINT:
	case AGPU_TEXTURE_FORMAT_R32G32B32_SINT:
        return 12;

	case AGPU_TEXTURE_FORMAT_R16G16B16A16_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R16G16B16A16_FLOAT:
	case AGPU_TEXTURE_FORMAT_R16G16B16A16_UNORM:
	case AGPU_TEXTURE_FORMAT_R16G16B16A16_UINT:
	case AGPU_TEXTURE_FORMAT_R16G16B16A16_SNORM:
	case AGPU_TEXTURE_FORMAT_R16G16B16A16_SINT:
        return 8;

	case AGPU_TEXTURE_FORMAT_R32G32_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R32G32_FLOAT:
	case AGPU_TEXTURE_FORMAT_R32G32_UINT:
	case AGPU_TEXTURE_FORMAT_R32G32_SINT:
        return 8;

	case AGPU_TEXTURE_FORMAT_R32G8X24_TYPELESS:
        return 8;

	case AGPU_TEXTURE_FORMAT_D32_FLOAT_S8X24_UINT:
	case AGPU_TEXTURE_FORMAT_R32_FLOAT_S8X24_TYPELESS:
	case AGPU_TEXTURE_FORMAT_X32_TYPELESS_G8X24_UINT:
        return 8;

	case AGPU_TEXTURE_FORMAT_R10G10B10A2_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R10G10B10A2_UNORM:
	case AGPU_TEXTURE_FORMAT_R10G10B10A2_UINT:
	case AGPU_TEXTURE_FORMAT_R11G11B10_FLOAT:
        return 4;

	case AGPU_TEXTURE_FORMAT_R8G8B8A8_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R8G8B8A8_UNORM:
	case AGPU_TEXTURE_FORMAT_R8G8B8A8_UNORM_SRGB:
	case AGPU_TEXTURE_FORMAT_R8G8B8A8_UINT:
	case AGPU_TEXTURE_FORMAT_R8G8B8A8_SNORM:
	case AGPU_TEXTURE_FORMAT_R8G8B8A8_SINT:
        return 4;

	case AGPU_TEXTURE_FORMAT_R16G16_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R16G16_FLOAT:
	case AGPU_TEXTURE_FORMAT_R16G16_UNORM:
	case AGPU_TEXTURE_FORMAT_R16G16_SNORM:
	case AGPU_TEXTURE_FORMAT_R16G16_SINT:
        return 4;

	case AGPU_TEXTURE_FORMAT_R32_TYPELESS:
	case AGPU_TEXTURE_FORMAT_D32_FLOAT:
	case AGPU_TEXTURE_FORMAT_R32_FLOAT:
	case AGPU_TEXTURE_FORMAT_R32_UINT:
	case AGPU_TEXTURE_FORMAT_R32_SINT:
        return 4;

	case AGPU_TEXTURE_FORMAT_R24G8_TYPELESS:
	case AGPU_TEXTURE_FORMAT_D24_UNORM_S8_UINT:
	case AGPU_TEXTURE_FORMAT_R24_UNORM_X8_TYPELESS:
	case AGPU_TEXTURE_FORMAT_X24TG8_UINT:
        return 4;

	case AGPU_TEXTURE_FORMAT_R8G8_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R8G8_UNORM:
	case AGPU_TEXTURE_FORMAT_R8G8_UINT:
	case AGPU_TEXTURE_FORMAT_R8G8_SNORM:
	case AGPU_TEXTURE_FORMAT_R8G8_SINT:
        return 2;

	case AGPU_TEXTURE_FORMAT_R16_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R16_FLOAT:
	case AGPU_TEXTURE_FORMAT_D16_UNORM:
	case AGPU_TEXTURE_FORMAT_R16_UNORM:
	case AGPU_TEXTURE_FORMAT_R16_UINT:
	case AGPU_TEXTURE_FORMAT_R16_SNORM:
	case AGPU_TEXTURE_FORMAT_R16_SINT:
        return 2;

	case AGPU_TEXTURE_FORMAT_R8_TYPELESS:
	case AGPU_TEXTURE_FORMAT_R8_UNORM:
	case AGPU_TEXTURE_FORMAT_R8_UINT:
	case AGPU_TEXTURE_FORMAT_R8_SNORM:
	case AGPU_TEXTURE_FORMAT_R8_SINT:
	case AGPU_TEXTURE_FORMAT_A8_UNORM:
        return 1;

/*
	case AGPU_TEXTURE_FORMAT_R1_UNORM = 66,
	case AGPU_TEXTURE_FORMAT_BC1_TYPELESS = 70,
	case AGPU_TEXTURE_FORMAT_BC1_UNORM = 71,
	case AGPU_TEXTURE_FORMAT_BC1_UNORM_SRGB = 72,
	case AGPU_TEXTURE_FORMAT_BC2_TYPELESS = 73,
	case AGPU_TEXTURE_FORMAT_BC2_UNORM = 74,
	case AGPU_TEXTURE_FORMAT_BC2_UNORM_SRGB = 75,
	case AGPU_TEXTURE_FORMAT_BC3_TYPELESS = 76,
	case AGPU_TEXTURE_FORMAT_BC3_UNORM = 77,
	case AGPU_TEXTURE_FORMAT_BC3_UNORM_SRGB = 78,
	case AGPU_TEXTURE_FORMAT_BC4_TYPELESS = 79,
	case AGPU_TEXTURE_FORMAT_BC4_UNORM = 80,
	case AGPU_TEXTURE_FORMAT_BC4_SNORM = 81,
	case AGPU_TEXTURE_FORMAT_BC5_TYPELESS = 82,
	case AGPU_TEXTURE_FORMAT_BC5_UNORM = 83,
	case AGPU_TEXTURE_FORMAT_BC5_SNORM = 84,
*/

	case AGPU_TEXTURE_FORMAT_B5G6R5_UNORM:
	case AGPU_TEXTURE_FORMAT_B5G5R5A1_UNORM:
        return 2;

	case AGPU_TEXTURE_FORMAT_B8G8R8A8_UNORM:
	case AGPU_TEXTURE_FORMAT_B8G8R8X8_UNORM:
	case AGPU_TEXTURE_FORMAT_B8G8R8A8_TYPELESS:
	case AGPU_TEXTURE_FORMAT_B8G8R8A8_UNORM_SRGB:
	case AGPU_TEXTURE_FORMAT_B8G8R8X8_TYPELESS:
	case AGPU_TEXTURE_FORMAT_B8G8R8X8_UNORM_SRGB:
        return 4;

    default:
        abort();
    }
}

inline bool hasDepthComponent(agpu_texture_format format)
{
    switch(format)
    {
    case AGPU_TEXTURE_FORMAT_D32_FLOAT_S8X24_UINT:
    case AGPU_TEXTURE_FORMAT_D32_FLOAT:
    case AGPU_TEXTURE_FORMAT_D24_UNORM_S8_UINT:
    case AGPU_TEXTURE_FORMAT_D16_UNORM:
        return true;
    default:
        return false;
    }
}

inline bool hasStencilComponent(agpu_texture_format format)
{
    switch(format)
    {
    case AGPU_TEXTURE_FORMAT_D32_FLOAT_S8X24_UINT:
    case AGPU_TEXTURE_FORMAT_D24_UNORM_S8_UINT:
        return true;
    default:
        return false;
    }
}

#endif //AGPU_TEXTURE_FORMATS_COMMON_HPP
